import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { CheckCircle2, CirclePlay, PackageCheck, Pencil, TriangleAlert, XCircle } from "lucide-react";
import { getUser, hasPermission } from "../../auth/services/authService";
import { cancelarOrdenProduccion, cambiarOperacionProduccion, liberarOrdenProduccion, obtenerOrdenProduccion, registrarAvanceProduccion, surtirOrdenProduccion } from "../services/ordenesProduccion";
import "./ordenesProduccion.css";

const ESTADOS={BORRADOR:"Borrador",LIBERADA:"Liberada",EN_PROCESO:"En proceso",TERMINADA:"Terminada",CANCELADA:"Cancelada"};
const numero=(v,d=2)=>Number(v||0).toLocaleString("es-MX",{minimumFractionDigits:d,maximumFractionDigits:d});

export default function OrdenProduccionDetallePage(){
  const {id}=useParams();const navigate=useNavigate();const user=getUser();
  const can=(p)=>hasPermission(user,p);const [orden,setOrden]=useState(null);const [error,setError]=useState("");const [procesando,setProcesando]=useState(false);
  const [surtido,setSurtido]=useState({});const [avances,setAvances]=useState({});
  const cargar=useCallback(async()=>{try{setOrden(await obtenerOrdenProduccion(id));setError("");}catch(e){setError(e.message);} },[id]);
  useEffect(()=>{cargar();},[cargar]);
  const activa=orden&&!['TERMINADA','CANCELADA'].includes(orden.estado);const opsPorPartida=useMemo(()=>(orden?.operaciones||[]).reduce((groups,item)=>{(groups[item.partidaId]??=[]).push(item);return groups;},{}),[orden]);
  const ejecutar=async(fn)=>{try{setProcesando(true);setError("");setOrden(await fn());}catch(e){setError(e.message||"No fue posible completar la acción");}finally{setProcesando(false);}};
  const liberar=()=>{if(window.confirm("La BOM y la ruta de operaciones quedarán congeladas. ¿Liberar esta orden?"))ejecutar(()=>liberarOrdenProduccion(id));};
  const cancelar=()=>{const motivo=window.prompt("Motivo de cancelación:");if(motivo?.trim())ejecutar(()=>cancelarOrdenProduccion(id,motivo.trim()));};
  const surtir=()=>{const insumos=orden.insumos.map(i=>({insumoId:i.insumoId,cantidad:Number(surtido[i.insumoId]||0)})).filter(i=>i.cantidad>0);if(!insumos.length){setError("Captura al menos una cantidad a surtir.");return;}ejecutar(()=>surtirOrdenProduccion(id,{insumos})).then?.(()=>setSurtido({}));};
  const avance=(p)=>{const cantidad=Number(avances[p.id]||0);if(cantidad<=0){setError("Captura una cantidad de avance mayor a cero.");return;}ejecutar(()=>registrarAvanceProduccion(id,p.id,{cantidad}));setAvances(x=>({...x,[p.id]:""}));};
  if(!orden)return <div className="op-page">{error?<div className="alert alert-danger">{error}</div>:<div className="op-empty">Cargando orden…</div>}</div>;
  return <div className="op-page"><button className="btn btn-link px-0" onClick={()=>navigate("/ordenes-produccion")}>← Volver</button>
    <header className="op-header"><div><div className="d-flex align-items-center gap-2"><h1 className="mb-0">{orden.folio}</h1><span className={`op-status op-status-${orden.estado.toLowerCase()}`}>{ESTADOS[orden.estado]}</span></div><p>{orden.origen==='COTIZACION'?`Cotización ${orden.cotizacionFolio}`:'Orden manual'} · {orden.clienteNombre||'Sin cliente'}</p></div>
      <div className="d-flex gap-2 flex-wrap">{orden.estado==='BORRADOR'&&can('ACTION_PRODUCTION_ORDERS_EDIT')&&<button className="btn btn-outline-primary" onClick={()=>navigate(`/ordenes-produccion/${id}/editar`)}><Pencil size={17}/> Editar programación</button>}{orden.estado==='BORRADOR'&&can('ACTION_PRODUCTION_ORDERS_RELEASE')&&<button disabled={procesando} className="btn btn-success" onClick={liberar}><CheckCircle2 size={17}/> Liberar</button>}{activa&&can('ACTION_PRODUCTION_ORDERS_CANCEL')&&<button disabled={procesando} className="btn btn-outline-danger" onClick={cancelar}><XCircle size={17}/> Cancelar</button>}</div>
    </header>{error&&<div className="alert alert-danger">{error}</div>}
    <section className="op-summary-grid"><div className="op-card op-summary"><span>Avance general</span><strong>{numero(orden.porcentajeAvance)}%</strong><div className="progress"><div className="progress-bar" style={{width:`${Math.min(100,orden.porcentajeAvance||0)}%`}}/></div></div><div className="op-card op-summary"><span>Inicio programado</span><strong>{orden.fechaInicioProgramada||'Sin fecha'}</strong></div><div className="op-card op-summary"><span>Fecha compromiso</span><strong>{orden.fechaCompromiso||'Sin fecha'}</strong></div><div className="op-card op-summary"><span>Materiales</span><strong className={orden.tieneFaltantes?'text-warning':'text-success'}>{orden.tieneFaltantes?'Con faltantes':'Disponibles'}</strong></div></section>
    {orden.motivoCancelacion&&<div className="alert alert-secondary"><strong>Motivo de cancelación:</strong> {orden.motivoCancelacion}</div>}
    <section className="op-card p-4 mb-4"><h4>Productos y avance</h4><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Producto</th><th>Planeado</th><th>Terminado</th><th>Avance</th><th></th></tr></thead><tbody>{orden.partidas.map(p=><tr key={p.id}><td><strong>{p.sku}</strong><br/><small>{p.nombre}</small></td><td>{numero(p.cantidadPlaneada,0)}</td><td>{numero(p.cantidadTerminada,0)}</td><td>{numero(p.porcentajeAvance)}%</td><td>{activa&&orden.estado!=='BORRADOR'&&can('ACTION_PRODUCTION_PROGRESS')&&<div className="input-group input-group-sm op-inline-action"><input type="number" min="0.001" step="0.001" className="form-control" placeholder="Avance" value={avances[p.id]||''} onChange={e=>setAvances(x=>({...x,[p.id]:e.target.value}))}/><button className="btn btn-outline-primary" disabled={procesando} onClick={()=>avance(p)}>Registrar</button></div>}</td></tr>)}</tbody></table></div></section>
    {orden.estado!=='BORRADOR'&&<section className="op-card p-4 mb-4"><div className="d-flex justify-content-between align-items-center"><h4>Materiales apartados</h4>{orden.tieneFaltantes&&<span className="text-warning"><TriangleAlert size={18}/> Apartado incompleto</span>}</div><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Insumo</th><th>Requerido</th><th>Surtido</th><th>Pendiente</th><th>Apartado</th><th>Por apartar</th><th>Existencia física</th><th>Surtir ahora</th></tr></thead><tbody>{orden.insumos.map(i=><tr key={i.id} className={i.faltante?'table-warning':''}><td><strong>{i.codigo}</strong><br/><small>{i.nombre}</small></td><td>{numero(i.requerido,4)} {i.unidad}</td><td>{numero(i.surtido,4)}</td><td>{numero(i.pendiente,4)}</td><td className="text-success fw-semibold">{numero(i.apartado,4)}</td><td>{numero(i.porApartar,4)}</td><td>{numero(i.existencia,4)}<br/><small className="text-muted">Libre: {numero(i.disponibleGeneral,4)}</small></td><td>{activa&&i.pendiente>0&&can('ACTION_PRODUCTION_MATERIAL_ISSUE')?<input className="form-control form-control-sm op-quantity" type="number" min="0" max={Math.min(i.pendiente,i.disponibleParaOrden)} step="0.0001" value={surtido[i.insumoId]||''} onChange={e=>setSurtido(x=>({...x,[i.insumoId]:e.target.value}))}/>:"—"}</td></tr>)}</tbody></table></div>{activa&&can('ACTION_PRODUCTION_MATERIAL_ISSUE')&&<div className="text-end"><button className="btn btn-primary" disabled={procesando} onClick={surtir}><PackageCheck size={17}/> Confirmar surtido</button></div>}</section>}
    {orden.estado!=='BORRADOR'&&<section className="op-card p-4 mb-4"><h4>Ruta de operaciones</h4>{orden.partidas.map(p=><div key={p.id} className="mb-4"><h6>{p.sku} · {p.nombre}</h6><div className="table-responsive"><table className="table table-sm align-middle"><thead><tr><th>#</th><th>Operación</th><th>Centro</th><th>Repeticiones</th><th>Tiempo</th><th>Estado</th><th></th></tr></thead><tbody>{(opsPorPartida[p.id]||orden.operaciones.filter(x=>x.partidaId===p.id)).map(op=><tr key={op.id}><td>{op.secuencia}</td><td>{op.codigo} · {op.nombre}</td><td>{op.centroTrabajo}</td><td>{op.repeticionesPlaneadas}</td><td>{numero(op.tiempoPlaneado)} min</td><td>{op.estado==='EN_PROCESO'?'En proceso':op.estado==='TERMINADA'?'Terminada':'Pendiente'}</td><td>{activa&&can('ACTION_PRODUCTION_PROGRESS')&&op.estado!=='TERMINADA'&&<button className={`btn btn-sm ${op.estado==='PENDIENTE'?'btn-outline-primary':'btn-outline-success'}`} disabled={procesando} onClick={()=>ejecutar(()=>cambiarOperacionProduccion(id,op.id,op.estado==='PENDIENTE'?'EN_PROCESO':'TERMINADA'))}>{op.estado==='PENDIENTE'?<><CirclePlay size={15}/> Iniciar</>:<><CheckCircle2 size={15}/> Terminar</>}</button>}</td></tr>)}</tbody></table></div></div>)}</section>}
    <section className="op-card p-4"><h4>Historial de avances</h4>{!orden.avances.length?<p className="text-muted mb-0">Aún no se han registrado avances.</p>:<div className="op-timeline">{orden.avances.map(a=><div key={a.id}><strong>+{numero(a.cantidad,3)} · {a.producto}</strong><span>{new Date(a.fechaRegistro).toLocaleString('es-MX')} · {a.usuario}</span>{a.observaciones&&<small>{a.observaciones}</small>}</div>)}</div>}</section>
  </div>;
}
